# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Generate ignition_config.json file and its base64 encoding
# Parameters: None
# Return: ignition_config_data
- name: "Set fact of Ignition config file path"
  ansible.builtin.set_fact:
    ignition_config_file: "{{ current_test_log_folder }}/ignition.json"
    ignition_sshd_config: "{{ 'PermitRootLogin yes\nPasswordAuthentication yes' | b64encode }}"

# Put SSH public key into ignition config file
- name: "Generation ignition config file {{ ignition_config_file }}"
  ansible.builtin.template:
    src: ignition_config.j2
    dest: "{{ ignition_config_file }}"
    mode: "0644"
  register: generate_ignition

- name: "Assert {{ ignition_config_file }} is generated"
  ansible.builtin.assert:
    that:
      - generate_ignition.changed
    fail_msg: "Failed to generate {{ ignition_config_file }}"
    success_msg: "Successfully generated {{ ignition_config_file }}"

- name: "Generate base64 encoded string for {{ ignition_config_file }}"
  ansible.builtin.set_fact:
    ignition_config_data: "{{ lookup('file', ignition_config_file) | b64encode }}"

- name: "Display base64 encoded data"
  ansible.builtin.debug: var=ignition_config_data
