# Copyright 2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Modify VM network config file before VM clone
- name: "Get guest network device manager"
  include_tasks: ../utils/get_network_manager.yml
  when: >-
    guest_os_network_manager is undefined or
    not guest_os_network_manager

- name: "Get primary network adapter information"
  include_tasks: ../utils/get_primary_network_adapter.yml

- name: "Change network config file before VM clone"
  include_tasks: ../network_device_ops/change_network_config_file.yml
