# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Reset deploy_casename in case user doesn't provide correct guest_id
- name: "Set fact of the deploy VM test case name"
  ansible.builtin.set_fact:
    deploy_casename: "deploy_vmwarephoton_ova"

# Photon OS OVA for HWv11 is using other3xlinux64 as guest id
- include_tasks: ../../../common/vm_set_guest_id.yml
  vars:
    guest_id: "vmwarePhoton64Guest"
  when:
    - vm_guest_id != "vmwarePhoton64Guest"
    - vm_hardware_version_num | int >= 13

# Create the seed ISO to modify login information
- include_tasks: ../../utils/create_seed_iso.yml
  vars:
    user_data_template: "photon-user-data.j2"
    local_hostname: "photon-{{ hostname_timestamp }}"

# Upload seed ISO to VM path on ESXi server
- include_tasks: ../../../common/esxi_upload_datastore_file.yml
  vars:
    src_file_path: "{{ seed_iso_path }}"
    dest_file_path: "{{ vm_dir_name }}/{{ seed_iso_path | basename }}"

# Attach seed ISO to Photon OS VM
- include_tasks: ../../../common/vm_configure_cdrom.yml
  vars:
    cdrom_type: iso
    cdrom_iso_file: "{{ vm_files_path_ds }}/{{ seed_iso_path | basename }}"
    cdrom_controller_num: 0
    cdrom_unit_num: 0
    cdrom_state: present

# Power on VM to update login information
- include_tasks: ../../common/vm_set_power_state.yml
  vars:
    vm_power_state_set: 'powered-on'
- include_tasks: ../../../common/vm_wait_guest_fullname.yml

# Get guest ip
- include_tasks: ../../../common/update_inventory.yml
  vars:
    update_inventory_timeout: 300

# Eject seed ISO from guest
- name: "Eject seed ISO from Photon OS"
  include_tasks: ../../utils/eject_cdrom_in_guest.yml
  vars:
    guest_cdrom_device_num: 0

# Disconnect seed ISO from Photon OS VM
- name: "Change VM's CD/DVD Drive 1 to client device"
  include_tasks: ../../../common/vm_configure_cdrom.yml
  vars:
    cdrom_type: client
    cdrom_controller_num: 0
    cdrom_unit_num: 0
    cdrom_state: present

# Remove temporary folders
- name: "Remove temporary directory {{ tmp_seed_dir }}"
  include_tasks: ../../../common/delete_local_file.yml
  vars:
    local_path: "{{ tmp_seed_dir }}"
