# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Reset deploy_casename in case user doesn't provide correct guest_id
- name: "Set fact of the deploy VM test case name"
  set_fact:
    deploy_casename: "deploy_vmwarephoton_ova"

# Photon OS OVA for HWv11 is using other3xlinux64 as guest id
- include_tasks: ../../../common/vm_set_guest_id.yml
  vars:
    vm_guest_id: "{{ guest_id }}"
  when:
    - guest_id == "vmwarePhoton64Guest"
    - vm_guest_id != guest_id
    - vm_hardware_version_num | int >= 13

# Create the seed.iso to modify login information
- include_tasks: ../../utils/create_seed_iso.yml
  vars:
    user_data_template: "photon-user-data.j2"
    local_hostname: "photon-{{ ansible_date_time.epoch }}"

# Upload seed.iso to VM path on ESXi server
- name: "Copy {{ seed_iso_path }} to VM folder"
  copy:
    src: "{{ seed_iso_path }}"
    dest: "{{ vm_path }}/{{ seed_iso_path | basename }}"
    force: yes
    mode: 0755
  delegate_to: "{{ esxi_hostname }}"

# Attach seed.iso to Photon OS VM
- name: "Set fact of the seed ISO path"
  set_fact:
    cdrom_seed_iso: "{{ vm_config.config.files.logDirectory }}/{{ seed_iso_path | basename }}"

- include_tasks: ../../../common/vm_configure_cdrom.yml
  vars:
    cdrom_type: iso
    cdrom_iso_file: "{{ cdrom_seed_iso }}"
    cdrom_controller_num: 0
    cdrom_unit_num: 0

# Power on VM to update login information
- include_tasks: ../../common/vm_set_power_state.yml
  vars:
    vm_power_state_set: 'powered-on'
- include_tasks: ../../../common/vm_wait_guest_fullname.yml

# Change root password for VM deployed from OVA
- include_tasks: change_root_password.yml

# Get guest ip
- include_tasks: ../../../common/update_inventory.yml
  vars:
    update_inventory_timeout: 300

# Eject seed.iso from guest
- name: "Eject seed.iso from Photon OS"
  include_tasks: ../../utils/eject_cdrom_in_guest.yml
  vars:
    guest_cdrom_device_num: 0

# Disconnect seed.iso from Photon OS VM
- name: "Change VM's CD/DVD Drive 1 to client device"
  include_tasks: ../../../common/vm_configure_cdrom.yml
  vars:
    cdrom_type: client
    cdrom_controller_num: 0
    cdrom_unit_num: 0

# Remove temporary folders
- name: "Remove temporary directory {{ tmp_seed_dir }}"
  include_tasks: ../../../common/delete_local_file.yml
  vars:
    local_path: "{{ tmp_seed_dir }}"
