# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Get specified property info for VM '{{ vm_name }}'"
  community.vmware.vmware_guest_info:
    hostname: "{{ vsphere_host_name }}"
    username: "{{ vsphere_host_user }}"
    password: "{{ vsphere_host_user_password }}"
    validate_certs: "{{ validate_certs | default(False) }}"
    datacenter: "{{ vsphere_host_datacenter }}"
    folder: "{{ vm_folder }}"
    name: "{{ vm_name }}"
    schema: "vsphere"
    properties: "{{ property_list | default(['config']) }}"
  register: get_vm_config_result

- name: Set fact of retrieved VM property info
  ansible.builtin.set_fact:
    vm_config: "{{ get_vm_config_result.instance }}"

- name: Display the VM config info
  ansible.builtin.debug: var=vm_config
  when: enable_debug is defined and enable_debug
