# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# create VM will fail if CDROM connects to the inaccessable ISO images
# so here to check if specified ISO file exists
- name: Display the configured CDROMs for guest OS installation
  debug: var=vm_cdroms

- include_tasks: ../../common/esxi_check_delete_datastore_file.yml
  vars:
    file_in_datastore: "{{ item.iso_path.split(']')[0].strip('[]') }}"
    file_in_datastore_path: "{{ item.iso_path.split(']')[1].strip(' ') }}"
    file_in_datastore_ops: "file"
    file_in_datastore_ops_timeout: 600
  with_items: "{{ vm_cdroms }}"
  when:
    - "'type' in item and item.type == 'iso'"
    - "'iso_path' in item and item.iso_path"
