name: Update copyright year(s) in files
on: workflow_dispatch
jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v2
        with:
          token: ${{ secrets.ASGV_CHANGE_COPYRIGHT }}
          branchName: license_{{ currentYear }}
          commitTitle: update license and copyright
          commitBody: Let's keep copyright up to date.
          commitAuthorName: 'Diane Wang'
          commitAuthorEmail: 'dianew@vmware.com'
          path: |
            NOTICE.txt
            LICENSE.txt
      - uses: FantasticFiasco/action-update-license-year@v2
        with:
          token: ${{ secrets.ASGV_CHANGE_COPYRIGHT }}
          branchName: license_{{ currentYear }}
          path: |
            common/*.yml
            env_setup/*.yml
            linux/**/*.yml
            plugin/ansible_vsphere_gosv_log.py
            vars/*.yml
            windows/**/*.yml
