name: Update copyright year(s) in files
jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v2
        with:
          token: ${{ secrets.ASGV_CHANGE_COPYRIGHT }}
          branchName: license_{{ currentYear }}
          commitTitle: update license and copyright
          commitBody: Let's keep copyright up to date.
          path: |
            NOTICE.txt
            LICENSE.txt
            "*.yml"
